### ISSUE TITLE
Add Stockholm to AWS regions

### ISSUE THREAD

**Issue by lffa** [bastionhost/cloudping#18]
Add Stockholm to AWS regions

**Comment by iamsk** [comment]
Added, thanks for your information !

**Comment by PatMyron** [comment]
some more AWS regions:
https://aws.amazon.com/jp/about-aws/whats-new/2018/02/announcing-the-aws-osaka-local-region/
https://aws.amazon.com/about-aws/whats-new/2018/11/announcing-the-new-aws-govcloud-us-east-region/
https://aws.amazon.com/blogs/aws/now-open-aws-middle-east-bahrain/
https://aws.amazon.com/blogs/aws/now-open-aws-europe-milan-region/
https://aws.amazon.com/blogs/aws/now-open-aws-africa-cape-town-region/
https://aws.amazon.com/blogs/aws/now-open-aws-asia-pacific-jakarta-region/
