### ISSUE TITLE
azure 悉尼节点可以加一下么?

### ISSUE THREAD

**Issue by riveryc** [bastionhost/cloudping#21]
Azure 也有悉尼的节点. :-)

**Comment by iamsk** [comment]
具体在哪里看到的，我查询 https://azure.microsoft.com/en-us/global-infrastructure/locations/ 并未发现

**Comment by riveryc** [comment]
> 具体在哪里看到的，我查询 https://azure.microsoft.com/en-us/global-infrastructure/locations/ 并未发现

你说的对... 其实: 
Australia East:  New South Wales = Sydney

那个新南威尔士洲其实特别大, 而悉尼是作为一个大城市存在的, 而不是一个区. 没关系, 既然他们那么写的, 我们就那么看吧, 只是会觉得比较奇怪... :) 多谢!
